Improve Rust vault color handling and cli options
NitorCreations/vault pull request #392
Opened 2024-03-19 08:19 UTC by Esgrove

- Use `colored` crate for handling ANSI colors instead of manually specifying codes
- Add a few missing long and short argument / command options
- Add usage to readme
- Use red color for error messages and tweak error texts to avoid repeating "Error: Error..."
- Simplify anyhow context usage
- Update all crate versions in cargo.toml

2024-03-22 12:03 UTC, kahlstrm requested changes

2024-03-22 12:03 UTC, kahlstrm commented on rust/src/cli.rs
> +        anyhow::bail!("Empty key '{key}'".red())
Same problem as with `delete`

2024-03-25 08:05 UTC, Esgrove commented on rust/Cargo.toml
>  base64 = "0.22.0"
It ensures the minimun version is at least that, which is significant. Dependabot updates for example always bumps these too. My question is why not do it.

2024-03-25 08:06 UTC, Esgrove commented on rust/Cargo.toml
> -tokio = { version = "1", features = ["full"] }
Explicit is better than implicit. Easier to see what version you actually are using with a quick glance.

2024-03-25 08:11 UTC, Esgrove commented on rust/src/cli.rs
> +        .context(format!("Failed to delete key '{key}'").red())
While that is true, I don't think having a few extra strings in memory is going to affect anything so I would go with the simpler code everytime instead of doing premature optimization. The lazy evaluation is only important if the context is particularly heavy or executed many times in a hot loop etc performance critical section. 

> Programmers waste enormous amounts of time thinking about, or worrying about, the speed of noncritical parts of their programs, and these attempts at efficiency actually have a strong negative impact when debugging and maintenance are considered. We should forget about small efficiencies, say about 97% of the time: premature optimization is the root of all evil. - Donald Knuth

2024-03-25 08:12 UTC, Esgrove commented on rust/src/cli.rs
> +        .context(format!("Failed to delete key '{key}'").red())
Also, I would be careful about trusting 3+ years old stack overflow answers since Rust has been evolving pretty fast, which is why I went to check the lib documentation that this is actually still the case:
https://docs.rs/anyhow/latest/anyhow/trait.Context.html#required-methods

2024-03-25 08:16 UTC, kahlstrm commented on rust/src/cli.rs
> +        .context(format!("Failed to delete key '{key}'").red())
Well the code was previously already written with this in mind, and now you're removing it for no apparent reason? 😄

2024-03-25 08:17 UTC, Esgrove commented on rust/src/cli.rs
> +        .context(format!("Failed to delete key '{key}'").red())
I can change them back if you absolutely want but personally I don't think it makes any real difference here from a performance point...

2024-03-25 08:24 UTC, kahlstrm commented on rust/src/cli.rs
> +        .context(format!("Failed to delete key '{key}'").red())
Performance stand point sure there is probably no noticeable difference, but in this case why not do it the correct way (as it already was -> less code change anyway) so it becomes a habit, at some point or another if you don't remember this difference with `with_context` and `context` it will probably surprise you then.

2024-03-25 08:34 UTC, Esgrove commented on rust/src/cli.rs
> +        .context(format!("Failed to delete key '{key}'").red())
ok, changing back and adding a note so I don't forget it and try to do it again in six months...

2024-03-25 09:34 UTC, kahlstrm approved these changes

2024-03-25 09:34 UTC, merged